export const Strings = {
  mobileBanking: 'Mobile banking the world\n loves.',
  getSendingText:
    'Get sending, spending and saving with your\ncontactless card.',
  getStartedWithAccount: 'Get started with your\naccount!',
  enterEmail: 'Email Address',
  password: 'Password',
  termsTextStart: "I have read and I understand Swift Pay Bank's ",
  termsConditions: 'Terms and conditions ',
  and: 'and ',
  PrivacyPolicy: 'Privacy Policy.',
  yourMobileNum: "What's your mobile number?",
  useAsAccNum: 'We’ll use this as your Swift Pay account number.',
  country: 'Country',
  agreementMsg:
    'By providing your phone number, you agree that we may contact you by SMS/text messaging. Carrier messaging and data rates may apply.',
  verifyPhn: 'Verify your phone number',
  otpHeading: 'Enter the 6-digit code we texted to you at ',
  editNumber: 'Edit Number',
  codeReceive: "Didn't receive the code?",
  resendCode: 'Resend code',
  openingText: 'Your Swift Pay account is\nopen, Victor!',
  announcementNews:
    'Great news, you’ve joined Swift Pay. You can\nnow make transfers and more.',
  accountInfo: 'Account Information',
  accountNum: 'Account Number',
  accountName: 'Account Name',
  institutionName: 'Institution Name',
  accountBalance: 'Account Balance',
  transactionHistory: 'Transaction History',
  accountSettings: 'Account Settings',
  logout: 'Logout',
  continueToApp: 'Continue to the app',
  login: 'Login',
  getStarted: 'Get Started',
  submit: 'Submit',
  verify: 'Verify',
};

export const ScreenNames = {
  AuthStack: 'AuthStack',
  BoardingScreen: 'OnBoardScreen',
  StartScreenOne: 'GetStartedScreenOne',
  StartScreenTwo: 'GetStartedScreenTwo',
  StartScreenThree: 'GetStartedScreenThree',
  StartScreenFour: 'GetStartedScreenFour',
  DashBoardScreen: 'DashBoardScreen',
};
